name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build specific Docker image
      run: docker build . --file Dockerfile --tag dcn_py:$(date +%s)

    - name: Build latest Docker image
      run: docker build . --file Dockerfile --tag dcn_py:latest
